name: Quadrupedal Robot Skateboarding
description: Research project on dynamic balance control for quadrupedal robots performing skateboarding maneuvers
baseurl: "/skateboardingrobot"
url: "https://thexuanphuc.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# SEO settings
title: Quadrupedal Robot Skateboarding
author: Research Team
lang: en
email: research@institution.edu

# Social settings
github_username: thexuanphuc
twitter_username: research_team

# Navigation
header_pages:
  - index.html
  - technical.html
  - publications.html
  - downloads.html

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
